//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Booking
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter your name.")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage = "Please enter your Grade.")]
        [Range (5,10, ErrorMessage="Grade must be between 5 and 10")]
        public string Grade { get; set; }
        [Required(ErrorMessage = "Please enter your address.")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please enter your Phone Number.")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please put your Gender.")]
        public string Gender { get; set; }
        public string MentorName { get; set; }
        public string MentorAddress { get; set; }
        [Required(ErrorMessage = "Please enter Subject.")]
        public string Subject { get; set; }
         [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dddd dd MMMM yyyy}")]
        [Required(ErrorMessage="You haven't choose StartDate.")]
        public Nullable<System.DateTime> StartDate { get; set; }
         [DataType(DataType.Time)]
         [Required(ErrorMessage = "You haven't choose time.")]
        public Nullable<System.TimeSpan> Time { get; set; }
    }
}
